[package]
name = "rust_crash_course"
version = "0.1.0"
authors = ["shubham"]
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
